version: 2

updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "15:00"
    groups:
      aws-sdk:
        patterns: 
          - "*"
